-- This problem set is pretty cool, let me get a chance to become a 'detective', using SQL to find information from database, I love it!
-- And I also found the SQL's power and interesting, I love cs50!
